meta: (( merge ))

networks: (( merge ))

releases:
  - name: diego
    version: latest
  - name: cf
    version: latest

external_cf_services: (( merge ))

etcd_cluster: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
consul_servers: (( jobs.consul_z1.networks.diego1.static_ips jobs.consul_z2.networks.diego2.static_ips jobs.consul_z3.networks.diego3.static_ips ))

jobs:
  - name: consul_z1
    release: diego
    templates:
      - name: consul-agent
    instances: 1
    persistent_disk: 1024
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          mode: server
          servers:
            lan: (( consul_servers ))

  - name: etcd_z1
    release: diego
    templates:
      - name: etcd
    instances: 1
    persistent_disk: 1024
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1

  - name: brain_z1
    release: diego
    templates:
      - name: consul-agent
      - name: auctioneer
      - name: converger
      - name: runtime_metrics_server
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z1
    networks:
      - name: diego1
    update:
      serial: true
    properties:
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z1
      consul:
        agent:
          servers:
            lan: (( consul_servers ))

  - name: cell_z1
    release: diego
    templates:
      - name: rep
      - name: consul-agent
      - name: executor
      - name: garden-linux
      - name: receptor
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z1
    networks:
      - name: diego1
    properties:
      consul:
        agent:
          services:
            - receptor
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z1
      diego:
        rep:
          zone: z1

  - name: cell_windows_z1
    release: diego
    templates:
      - name: rep
      - name: consul-agent
      - name: executor
      - name: garden-windows
      - name: receptor
      - name: metron_agent
        release: cf
    instances: 0
    resource_pool: large_z1
    networks:
      - name: diego1
    properties:
      consul:
        agent:
          services:
            - receptor
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z1

  - name: cc_bridge_z1
    release: diego
    templates:
      - name: stager
      - name: nsync
      - name: tps
      - name: file_server
      - name: consul-agent
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: bridge_z1
    networks:
      - name: diego1
    properties:
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z1
      consul:
        agent:
          services:
            - stager
            - file_server
          servers:
            lan: (( consul_servers ))

  - name: route_emitter_z1
    release: diego
    templates:
      - name: route_emitter
      - name: consul-agent
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      consul:
        agent:
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z1

  - name: consul_z2
    release: diego
    templates:
      - name: consul-agent
    instances: 1
    persistent_disk: 1024
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          mode: server
          servers:
            lan: (( consul_servers ))

  - name: etcd_z2
    release: diego
    templates:
      - name: etcd
    instances: 0
    persistent_disk: 1024
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1

  - name: brain_z2
    release: diego
    templates:
      - name: consul-agent
      - name: auctioneer
      - name: converger
      - name: runtime_metrics_server
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z2
    networks:
      - name: diego2
    update:
      serial: true
    properties:
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z2
      consul:
        agent:
          servers:
            lan: (( consul_servers ))

  - name: cell_z2
    release: diego
    templates:
      - name: rep
      - name: consul-agent
      - name: executor
      - name: garden-linux
      - name: receptor
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z2
    networks:
      - name: diego2
    properties:
      consul:
        agent:
          services:
            - receptor
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z2
      diego:
        rep:
          zone: z2

  - name: cell_windows_z2
    release: diego
    templates:
      - name: rep
      - name: consul-agent
      - name: executor
      - name: garden-windows
      - name: receptor
      - name: metron_agent
        release: cf
    instances: 0
    resource_pool: large_z2
    networks:
      - name: diego2
    properties:
      consul:
        agent:
          services:
            - receptor
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z2

  - name: cc_bridge_z2
    release: diego
    templates:
      - name: stager
      - name: nsync
      - name: tps
      - name: file_server
      - name: consul-agent
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: bridge_z2
    networks:
      - name: diego2
    properties:
      nats: (( external_cf_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z2
      consul:
        agent:
          services:
            - stager
            - file_server
          servers:
            lan: (( consul_servers ))

  - name: route_emitter_z2
    release: diego
    templates:
      - name: route_emitter
      - name: consul-agent
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      consul:
        agent:
          servers:
            lan: (( consul_servers ))
      loggregator_endpoint:
        shared_secret: (( external_cf_services.loggregator_endpoint.shared_secret ))
      metron_agent:
        zone: z2

  - name: consul_z3
    release: diego
    templates:
      - name: consul-agent
    instances: 1
    persistent_disk: 1024
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          mode: server
          servers:
            lan: (( consul_servers ))

  - name: etcd_z3
    release: diego
    templates:
      - name: etcd
    instances: 0
    persistent_disk: 1024
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1

properties:
  # -- Properties below are used by jobs from cf-release --
  nats: # For metron_agent to talk to collector
    machines: (( external_cf_services.nats.machines ))
    user: (( external_cf_services.nats.user ))
    password: (( external_cf_services.nats.password ))
    port: (( external_cf_services.nats.port ))

  etcd: # For metron_agent to find loggregator
    machines: (( external_cf_services.etcd.machines ))

  syslog_daemon_config: ~

  diego:
    # -- Global properties --
    api_url: (( "http://" receptor.username ":" receptor.password "@receptor.service.dc1.consul:8888" ))

    ssl:
      skip_cert_verify: false

    nats: (( external_cf_services.nats ))

    etcd:
      machines: (( etcd_cluster ))

    # -- Helper alias --
    cc_config:
      base_url: (( external_cf_services.cc.srv_api_uri ))
      basic_auth_password: (( external_cf_services.cc.internal_api_password ))
      staging_upload_user: (( external_cf_services.cc.staging_upload_user ))
      staging_upload_password: (( external_cf_services.cc.staging_upload_password ))

    etcd_config:
      machines: (( etcd_cluster ))

    nats_config:
      machines: (( external_cf_services.nats.machines ))
      username: (( external_cf_services.nats.user ))
      password: (( external_cf_services.nats.password ))
      port: (( external_cf_services.nats.port ))

    # -- Job specific properties --
    auctioneer:
      etcd: (( etcd_config ))
      log_level: info

    converger:
      etcd: (( etcd_config ))
      log_level: info

    executor:
      allow_privileged: ~
      drain_timeout_in_seconds: ~
      export_network_env_vars: ~
      garden: ~
      log_level: info

    file_server:
      cc: (( cc_config ))
      log_level: info

    nsync:
      diego_api_url: (( .properties.diego.api_url ))
      cc: (( cc_config ))
      etcd: (( etcd_config ))
      lifecycle_bundles: ~
      nats: (( nats_config ))

    receptor:
      cors_enabled: false
      domain_names: ~
      etcd: (( etcd_config ))
      nats: (( nats_config ))
      username: ""
      password: ""
      register_with_router: false
      log_level: info

    rep:
      etcd: (( etcd_config ))
      log_level: info

    route_emitter:
      diego_api_url: (( .properties.diego.api_url ))
      etcd: (( etcd_config ))
      nats: (( nats_config ))
      log_level: info

    runtime_metrics_server:
      etcd: (( etcd_config ))
      nats: (( nats_config ))

    stager:
      cc: (( cc_config ))
      diego_api_url: (( .properties.diego.api_url ))
      lifecycle_bundles: ~
      nats: (( nats_config ))
      log_level: info

    tps:
      diego_api_url: (( .properties.diego.api_url ))
      nats: (( nats_config ))
      log_level: info

    garden-linux: ~
    garden-windows: ~
